### PR TITLE
WIP Attempt windows build…

### PR DESCRIPTION
**Pull request by kastman**
Following https://github.com/erikd/libsndfile/blob/master/appveyor.yml and readme.md

### CODE REVIEW

**Comment by kastman** [comment]
@conda-forge-admin, please rerender

**Comment by kastman** [comment]
Hi @hbredin and @thomasfillon ,

I'm trying to add a Windows build to libsndfile, and am getting stuck. At this point I'm using the conda-forge toolchain, which is grabbing `MSVC 19.0.24215.1`, but [CMake logs](https://ci.appveyor.com/project/conda-forge/libsndfile-feedstock/build/1.0.13#L412) looks like it's trying to use `MSVC 14` and the [appveyor.yaml](https://github.com/erikd/libsndfile/blob/master/appveyor.yml#L16) provided upstream looks like it targets `MSVC 15` (and uses static linking, which I don't think we want for the conda distribution). Any suggestions to either bring them up or down so that everything's in line? My windows packaging is quite weak.

Additionally, the CMakeLists.txt file wasn't in the tarball currently in conda-forge (1.27), so I updated it to 1.28. However, it looks like that cmake is still trying to use automake / autoconf and is looking for a `configure.ac` file, but as far as I understand that's incorrect for windows (the automake package in conda-forge is disabled on windows, for example). 

Any suggestions on how to get this to build? Planning to use it upstream in [psychopy](https://github.com/conda-forge/staged-recipes/pull/5739). Thanks,

**Comment by hbredin** [comment]
I have no experience in Windows build, sorry.

Also, I am no longer able to maintain this recipe.
If you feel like this is something you could do and @thomasfillon is OK, then I suggest you become one of the maintainers.

**Comment by kastman** [comment]
@thomasfillon Any suggestions on the windows build? I'm alright maintaining since @hbredin is unavailable, but need help with this one.

**Comment by thomasfillon** [comment]
Hi @kastman !

Thanks for your help on maintaining this recipe. Maybe you need to join the conda-forge organization: https://github.com/conda-forge. 

Unfortunately, I don't have any experience either regarding Windows build.

Maybe @SylvainCorlay could help ?

**Comment by thomasfillon** [comment]
I've just merge #6 to update libsndfile version to 1.0.28. Could you merge the master branch back into your PR branch, please.

**Comment by SylvainCorlay** [comment]
The master branch of libsndfile builds without issue with cmake on windows but not  the last release (1.0.28).

I have opened https://github.com/erikd/libsndfile/issues/375 asking the package authors if they would like to tag a release including these fixes. (Please upvote!)

**Comment by kastman** [comment]
Thanks @SylvainCorlay and @thomasfillon . It would be great if upstream were fixed, but what are some other alternatives? I could add the CMake changes as a patch to this version if they're relatively simple, but I agree that an update from upstream would be the cleanest. 

I pulled in the auto-tick from master, so the versions should be in sync again. Thanks,

**Comment by tjwilli58** [comment]
@kastman , I don't know anything about Windows builds either, but I did a little searching, and I did find a [repository ](https://github.com/lordmulder/libsndfile-MSVC) by @lordmulder that may help. 

> Static libsndfile for use with Microsoft Visual C++, ported by LoRd_MuldeR <mulder2@gmx.de>
> 
> Details
> Libsndfile is a C library for reading and writing files containing sampled sound (such as MS Windows WAV and the Apple/SGI AIFF format) through one standard library interface. Unfortunately, the "official" version of libsndfile does not currently support building the library with Microsoft Visual C++ (MSVC). It is still possible to build a Windows DLL of libsndfile with MinGW/GCC and then link the MinGW-compiled DLL against your MSVC-compiled program files. However, to the best of my knowledge, this method does not work if you intend to link libsndfile as a static library! At least I never got it to work ;-)
> 
> The purpose of this repository is providing solution/project files that can be used to compile the latest version of libsndfile under MSVC, resulting in a "native" MSVC library that allows for static linking with MSVC-compiled programs. The code in this repository is identical to the "official" libsndfile codebase, except that solution/project files for MSVC have been added and that config.h has been adjusted. Furthermore, a few compatibility (build) fixes were required for MSVC, some of which were backported from the Qt Framework. In my tests, the MSVC binary of libsndfile is only slightly slower than the MinGW one.
> 
> My project/solution files have been tested to build smoothly under Visual Studio 2013 (MSVC 12.0) or 2015 (MSVC 14.0).
> 
> 

I'm very interested in your success in getting this for [psychopy ](https://github.com/conda-forge/staged-recipes/pull/5739)also!

**Comment by kastman** [comment]
@conda-forge-admin please rerender

**Pull request closed without merging**
